name: Codecov

on:
  push:
    branches:
      - codecov-prove

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: xcpretty/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and test
        run: |
          xcodebuild clean test -scheme ionixTest -destination 'platform=iOS Simulator,name=iPhone 13' | xcpretty

      - name: Generate coverage report
        run: |
          xcrun llvm-cov export -format=lcov -ignore-filename-regex='.*Tests.*' ionixTest > coverage.lcov
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          


